# Global users and groups

- group_config:

    - cuhu_global_authors:

       - name: Tetra Pak global content authors group
         memberOf: content-authors
         path: /home/groups/cuhugroups

    - cuhu_super_users:

        - name: Tetra Pak super users group
          memberOf: fragment-editor,fragment-templateauthor
          path: /home/groups/cuhugroups

- ace_config:

    - cuhu_global_authors:

       - path: /content/tetrapak
         permission: allow
         privileges: jcr:modifyAccessControl,jcr:read,jcr:readAccessControl,crx:replicate,jcr:versionManagement,rep:write,jcr:lockManagement

       - path: /content/dam/tetrapak
         permission: allow
         privileges: jcr:modifyAccessControl,jcr:read,jcr:readAccessControl,crx:replicate,jcr:versionManagement,rep:write,jcr:lockManagement

       - path: /etc/languages
         permission: allow
         actions: read
         privileges:

    - cuhu_super_users:

        - path: /conf/customerhub
          permission: allow
          actions: read,modify,create,delete,replicate
          privileges:
          repGlob:

        - path: /content/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /content/tetrapak/customerhub
          permission: allow
          actions: read,create,modify,delete,replicate
          privileges:
          repGlob:

        - path: /content/dam/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /content/dam/tetrapak
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /content/dam/tetrapak/customerhub
          permission: allow
          actions: read,create,modify,delete,replicate
          privileges:
          repGlob:

        - path: /apps/cq/core/content/nav/tools
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /apps/cq/core/content/nav/tools
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /apps/cq/core/content/nav/tools/acs-commons
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: ""

        - path: /apps/cq/core/content/nav/tools/acs-commons
          permission: allow
          actions:
          privileges: jcr:read,jcr:readAccessControl
          repGlob: /jcr:content

        - path: /apps/cq/core/content/nav/tools/acs-commons/generic-lists
          permission: allow
          actions: read
          privileges:
          repGlob:

        - path: /etc/acs-commons/lists
          permission: allow
          actions: read,modify,create,delete,replicate
          privileges:
          repGlob:

